# Site settings
title: Christopher C. Paone
email: paone@siu.edu
description: > # this means to ignore newlines until "baseurl:"
  I am a Ph.D. candidate in the Philosophy Department at Southern Illinois University in Carbondale, Illinois. My research focuses on ancient Greek and Roman philosophy and ethical theory. I have defended my dissertation and will be graduated in May 2015.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://paonec.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
